# Travis CI Configuration File


language:   php
#sudo:       false
#dist:       trusty

php:
#  - 5.3
#  - 5.4
#  - 5.5
  - 5.6
#  - 7.0
#  - hhvm
matrix:
  allow_failures:
#  - php: 7.0
  - php: 5.6

env:
#    - MAGENTO_VERSION=magento-mirror-1.9.3.0 MAGENTO_DB_ALLOWSAME=1 
    - MAGENTO_VERSION=magento-mirror-1.9.3.6 MAGENTO_DB_ALLOWSAME=1
#  - MAGENTO_VERSION=magento-ce-1.9.0.1
#  - MAGENTO_VERSION=magento-ce-1.8.1.0
#  - MAGENTO_VERSION=magento-ce-1.8.0.0
#  - MAGENTO_VERSION=magento-ce-1.7.0.2

install:
    # Run Composer
    - composer update --no-dev --ignore-platform-reqs
    
    # Configure Php ...
    - phpenv config-rm xdebug.ini
    - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    # Install Magento & Modules
    - bash build/setup.sh
    
    # Configure Splash Module
    - bash build/configure.sh    

before_script:
    - cd /tmp/magetest
    
    # Print Installation Infos
    - php -r "echo date_default_timezone_get();"
    - tools/n98-magerun.phar --root-dir=htdocs sys:modules:list   
    - tools/n98-magerun.phar --root-dir=htdocs config:get general/locale/* 

script:
    - cd /tmp/magetest/htdocs
    - phpunit
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_failure:
