# Travis CI Configuration File
language:   php

matrix:
    include:
          
        # Magento 1.9 Branch       
        - php: 5.6
          env: MAGENTO_VERSION=magento-mirror-1.9.0.1    
        - php: 5.6
          env: MAGENTO_VERSION=magento-mirror-1.9.3.6    
        - php: 7.0
          env: MAGENTO_VERSION=magento-mirror-1.9.3.6    
        - php: 7.1
          env: MAGENTO_VERSION=magento-mirror-1.9.3.6    
          
    allow_failures:
        - env: DOL_VERSION=develop DATA_VERSION=7.0.0
          
    fast_finish: true
    
install:
    # Run Composer
    - composer update --no-dev --ignore-platform-reqs
    
    # Configure Php ...
    - phpenv config-rm xdebug.ini
#    - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    # Install Magento & Modules
    - sh build/setup.sh
    
    # Configure Splash Module
    - sh build/configure.sh    

script:
    - cd /tmp/magetest/htdocs
    - phpunit
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_failure:
    
    # Print Installation Infos
    - phpunit --version
    - php -r "echo date_default_timezone_get();"
    - cd /tmp/magetest
    - ./n98-magerun.phar --version
    - ./n98-magerun.phar --root-dir=htdocs sys:info   
    - ./n98-magerun.phar --root-dir=htdocs sys:store:list   
    - ./n98-magerun.phar --root-dir=htdocs sys:modules:list   
    - ./n98-magerun.phar --root-dir=htdocs eav:attribute:list
    - ./n98-magerun.phar --root-dir=htdocs config:get general/store_information/*     
    - ./n98-magerun.phar --root-dir=htdocs config:get general/locale/*     
