###########################################################
# Main Configuration
###########################################################
site_name: Magneto 1 Splash Bundle 
site_dir: "../../../../../../docs"
theme: readthedocs

repo_url: https://github.com/SplashSync/Magento1

copyright:  <i class="fa fa-copyright" aria-hidden="true"></i> Copyright Splash Sync 2018 

###########################################################
# Site Contents
###########################################################
pages:
    - Home:                     index.md
    - Features:                 features.md
    - Installation:             install.md
    - Configuration:            configuration.md
#    - Test & Connect: connect.md
    - Documentation Française :
        - Accueil :             fr/index.md
        - Fonctionnalités:      fr/features.md
        - Installation:         fr/install.md
        - Configuration:        fr/configuration.md        
#    - About: about.md